PUBLIC REAL_NUM
PUBLIC READ_NUM
PUBLIC NUM
PUBLIC NEG_FLAG
PUBLIC MAX_SIZE
PUBLIC LEN
PUBLIC BIN_STR
PUBLIC HEX_STR
EXTRN NEW_LINE: NEAR
EXTRN TO_REAL_NUM: NEAR
EXTRN TO_BIN: NEAR
EXTRN TO_HEX: NEAR
DATAS SEGMENT PARA PUBLIC 'DATA'
    MAX_SIZE DB 6
    LEN DB 0
    NUM DB 5 DUP ("0"), "$"

    BIN_STR DB 16 DUP ("0"), "$"

    NEG_FLAG DB 0

    HEX_STR DB 5 DUP ("0"), "$"

    REAL_NUM DW 0

    INVITE_MSG DB "Input number: $"
DATAS ENDS

CODES SEGMENT PARA PUBLIC 'CODE'
    ASSUME CS:CODES, DS:DATAS
READ_NUM:
    CALL INIT_NUM
    CALL NEW_LINE

    MOV AH, 9
    MOV DX, OFFSET INVITE_MSG
    INT 21H

    MOV AH, 0Ah
    MOV DX, OFFSET MAX_SIZE
    INT 21H

    CALL TO_REAL_NUM
    CALL TO_BIN
    CALL TO_HEX
    CALL NEW_LINE

    RET
INIT_NUM:
    MOV LEN, 0
    MOV REAL_NUM, 0

    MOV AX, SEG NUM
    MOV ES, AX
    MOV DI, OFFSET NUM
    MOV AL, "0"
    MOV CX, 6
    REP STOSB

    MOV AX, SEG BIN_STR
    MOV ES, AX
    MOV DI, OFFSET BIN_STR
    MOV AL, "0"
    MOV CX, 16
    REP STOSB

    MOV AX, SEG HEX_STR
    MOV ES, AX
    MOV DI, OFFSET HEX_STR
    MOV AL, "0"
    MOV CX, 5
    REP STOSB

    RET
CODES ENDS
END

